export enum EventDayState {
    NOT_IN_SALE = "NOT_IN_SALE",
    RESERVABLE_AND_BUYABLE = "RESERVABLE_AND_BUYABLE",
    ONLY_BUYABLE = "ONLY_BUYABLE",
    SOLD_OUT = "SOLD_OUT",
    CANCELLED = "CANCELLED"
}